POST  https://localhost:8000/api/login_check
Content-Type: application/json

{
"username": "admin@afpa.fr",
"password": "admin"
}

###

GET https://localhost:8000/api/users/
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MzE1MTcwNzMsImV4cCI6MTczMTUyMDY3Mywicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQGFmcGEuZnIifQ.OZ7lrkdrk6KGLs0wQ_3ANGcc1cuOGOF2JDRltuyX-BtSdHanr7NHBzN3wDWedxxQpto8OmlZnVA7lDVyT82F65TQiWEOXHrab0ce24IJCqYB_LKyJCm-acWoPW1kqhtWcZ6ZbCzHwNQ4F-KKGFfxQSdN9smbYzDRK0b7pFgUQFLozribX0rOWnVmOy19hkCtLspotcG7Yo_AcY585SK1mHo8_xeNToxd0_KxTux1kiu-uHtFxIkYrgrT9WM_tIl-41rT42K426OWT6iqbbWmS_yI-C464NLLVp4rsTt4CGaACFlBfzLYbUPe_dUOpDQAdV19B31Oe4qO55nb_bkzfQ

{

}