POST  https://localhost:8000/api/login_check
Content-Type: application/json

{
"username": "admin@afpa.fr",
"password": "admin"
}

###

GET https://localhost:8000/api/users/
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MzE1MTAxODgsImV4cCI6MTczMTUxMzc4OCwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQGFmcGEuZnIifQ.U7-0yvW1Q1ZrS1DogA47l28tYWwF3wVhuJo6qh5sobq3_4ZCKd-1rhaSFfDWX0SYIsr990tfcgn10wywhQ_tIsmXygGMw0dswXk_Cxv3xdhtpx4gtU5R2UUF7xK47g8tdmsYwCMhN5i0irjj9VMoOvV18eO6R3lD4Hesb9C6t2VHwVGnuaDOypoP5sG2-pAH1cpC6mSnRV4YJKDSGAtbOnkzcnsvWTx7eVLA0lL5p9dR6Mof_F5Y3jh9VW3RHF54hTcjNhiwGS-4rwAHK_J9JiX9N-wReF3HcHTyunlixnJ3A6iNu_qG16YzMRp5hhXeSf9yHN4jdajjmGe9Etu8qQ

{

}